### PR TITLE
add options router

### PR DESCRIPTION
**Pull request by JTCunning**

### CODE REVIEW

**Comment by aalpern** [comment]
:boom: :heart:

**Comment by thekad** [comment]
Can you add a bit more background on the doc section? I know what this is for (sort of) because we talked about it in person, but is not readily apparent just wtf this endpoint could be used for. Tentative +1 otherwise.

**Comment by aalpern** [comment]
I'm guessing this is needed here because it's either extremely difficult or impossible to get Apache configured to handle the OPTIONS requested needed for CORS without it existing in the proxied service?

**Comment by JTCunning** [comment]
I mean.. I was going to add more to this so that it actually can survive without a proxy, and so that we didn't have to statically define headers outside of the actual app and stuff like that.

**Pull request merged**
